### ISSUE TITLE
Could not open the ETensemble data

### ISSUE THREAD

**Issue by Thuybui1410** [wateraccounting/SEBAL#2]
Hi,
I have downloaded Water Accounting Plus Toolbox and install all the python modules successfully. I have run the code as the instruction: 
import wa
from wa.Products import ETens
ETens.monthly(Dir='C:/Temp/', Startdate='2003-12-01', Enddate='2003-12-20', latlim=[12, 13], lonlim=[107, 108])
When I open Temp folder, I could not open my image. It is in TIFF file and 8 bytes.
Looking forward your reply, thanks a lot.

**Comment by TimHessels** [comment]
Hi,

Lets start with checking some general stuff. Below you will find some steps that has to be done:

Did you fill in the right password and username within the webaccounts.py located in the main "wa" folder?

Did you create a WA_PATHS folder within the environment variables?

Do you have a GDAL_DATA folder?

If one of those steps above are missing, I can give you more information about one of the steps that you need to do to get it running. If all above steps are fine, we will go more in detail.

Best regards,
Tim


________________________________
Van: Thuybui1410 <notifications@github.com>
Verzonden: maandag 14 mei 2018 20:03
Aan: wateraccounting/SEBAL
CC: Subscribed
Onderwerp: [wateraccounting/SEBAL] Could not open the ETensemble data (#2)


Hi,
I have downloaded Water Accounting Plus Toolbox and install all the python modules successfully. I have run the code as the instruction:
import wa
from wa.Products import ETens
ETens.monthly(Dir='C:/Temp/', Startdate='2003-12-01', Enddate='2003-12-20', latlim=[12, 13], lonlim=[107, 108])
When I open Temp folder, I could not open my image. It is in TIFF file and 8 bytes.
Looking forward your reply, thanks a lot.

**Comment by Thuybui1410** [comment]
Hi Tim,
Thank you so much for your quick reply.
I have changed the username and password within the webaccounts.py. 

In User Variables I have changed:
Variable name                   Variable value
GDAL_DATA                       C:\Program Files\GDAL

In System variables I also add: 
WA_HOME                        C:\Users\bicht\Documents\WA_HOME
WA_PATHS                        C:\Users\bicht\Documents\WA_HOME;C:\Users\bicht\Documents\WA_HOME

In addition, I can import wa and import gdal successfully without any bug.
Once again, thanks a lot for your support.
Best regards,
Thuy

**Comment by TimHessels** [comment]
When you run the code, what error do you get?

Best regards,
Tim
________________________________
Van: Thuybui1410 <notifications@github.com>
Verzonden: dinsdag 15 mei 2018 20:51
Aan: wateraccounting/SEBAL
CC: TimHessels; Comment
Onderwerp: Re: [wateraccounting/SEBAL] Could not open the ETensemble data (#2)


Dear Tim,
Thank you so much for your help. I have changed as your instruction but I still can not open the ET map. I think the problems may come from my environment variable. Could you please help me check the environment variable:

User variables:

  1.  GDAL_DATA: C:\Program Files\GDAL\gdal-data
2.Path: %USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\GDAL;

System variables:
1.Path:C:\Program Files\GDAL;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;
2.WA_HOME: C:\Users\bicht\Documents\WA_HOME
3.WA_PATHS:C:\Program Files\GDAL;C:\Program Files\Inkscape;

Whether I need to add the add the Anacoda2 to the Path in user variables or system variables ?

Looking forward for your reply,
Best regards,
Thuy

**Comment by Thuybui1410** [comment]
Hi Tim,

There is no explanation or warnings about the errors. It looks like this in
my Spyder ( picture below). In Temp folder I could find the TIFF image with
8bytes and I could not open the image.

I really hope that you can help me to find the problems and once again
thank you very much.
Best regards,
Thuy

**Comment by TimHessels** [comment]
Do you have teamviewer, so I can check this?
________________________________
Van: Thuybui1410 <notifications@github.com>
Verzonden: woensdag 16 mei 2018 00:17
Aan: wateraccounting/SEBAL
CC: TimHessels; Comment
Onderwerp: Re: [wateraccounting/SEBAL] Could not open the ETensemble data (#2)

Hi Tim,

There is no explanation or warnings about the errors. It looks like this in
my Spyder ( picture below). In Temp folder I could find the TIFF image with
8bytes and I could not open the image.

I really hope that you can help me to find the problems and once again
thank you very much.
Best regards,
Thuy

**Comment by Thuybui1410** [comment]
Yes I have Teamviewer so just let me know when you are available . Currently, I live in Belgium (GMT+2).
Thank you very much for your help, I really appreciate.
Best regards,
Thuy

**Comment by TimHessels** [comment]
Dear Thuy,

Can you send your e-mail adress to t.hessels@un-ihe.org? Then I will contact you, when I am available.

Best regards,
Tim
________________________________
Van: Thuybui1410 <notifications@github.com>
Verzonden: woensdag 16 mei 2018 10:08
Aan: wateraccounting/SEBAL
CC: TimHessels; Comment
Onderwerp: Re: [wateraccounting/SEBAL] Could not open the ETensemble data (#2)


Yes I have Teamviewer so just let me know when you are available . Currently, I live in Belgium (GMT+2).
Thank you very much for your help, I really appreciate.
Best regards,
Thuy
